name: "Publish"
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Zondax Harbor Registry
        uses: docker/login-action@v1
        with:
          registry: harbor.int.zondax.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build Container Image
        run: |
          export GIT_HASH=$(git rev-parse HEAD)
          docker build --rm -f Dockerfile -t harbor.int.zondax.net/zondax/zxtestrunner:latest -t harbor.int.zondax.net/zondax/zxtestrunner:$GIT_HASH .
      - name: Push to Zondax Harbor Registry
        run: |
          export GIT_HASH=$(git rev-parse HEAD)
          docker push harbor.int.zondax.net/zondax/zxtestrunner:latest
          docker push harbor.int.zondax.net/zondax/zxtestrunner:$GIT_HASH
